platform :ios, '9.0'

target 'BitcoinTicker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BitcoinTicker

  pod 'SwiftyJSON'
  pod 'Alamofire'

end
